/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:56062e07-c83d-45f5-b17d-dc1d14a03be0",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_0vvRmPnjC",
    "aws_user_pools_web_client_id": "1k1rbko2j6ksd9giob660npej2",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ibf7d2ysvbcebm2nsw7chcnw2u.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hlkwymhf5rcm7cwnyitpahhbpy",
    "aws_user_files_s3_bucket": "amplifyappdf4657cbae4e4386a15a08a5ff13e939231145-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
